# Generated by Django 3.2.5 on 2021-08-03 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('characters', models.ManyToManyField(to='lore.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('characters', models.ManyToManyField(to='lore.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('characters', models.ManyToManyField(to='lore.Character')),
                ('events', models.ManyToManyField(to='lore.Event')),
                ('factions', models.ManyToManyField(to='lore.Faction')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mood_media_link', models.CharField(blank=True, max_length=2048)),
                ('description', models.TextField(blank=True)),
                ('characters', models.ManyToManyField(to='lore.Character')),
                ('events', models.ManyToManyField(to='lore.Event')),
                ('factions', models.ManyToManyField(to='lore.Faction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_owner', to=settings.AUTH_USER_MODEL)),
                ('places', models.ManyToManyField(to='lore.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('characters', models.ManyToManyField(to='lore.Character')),
                ('factions', models.ManyToManyField(to='lore.Faction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='faction',
            name='items',
            field=models.ManyToManyField(to='lore.Item'),
        ),
        migrations.AddField(
            model_name='faction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faction',
            name='places',
            field=models.ManyToManyField(to='lore.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='factions',
            field=models.ManyToManyField(to='lore.Faction'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.ManyToManyField(to='lore.Place'),
        ),
        migrations.AddField(
            model_name='character',
            name='events',
            field=models.ManyToManyField(to='lore.Event'),
        ),
        migrations.AddField(
            model_name='character',
            name='factions',
            field=models.ManyToManyField(to='lore.Faction'),
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(to='lore.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='places',
            field=models.ManyToManyField(to='lore.Place'),
        ),
    ]
